### PR TITLE
Center team cards on overflow

### PR DESCRIPTION
**Pull request by scottgigante-immunai**
Currently the overflowing cards align left. Moving to flex aligns them to the centre.

### CODE REVIEW

**Comment by scottgigante-immunai** [comment]
Hmm, this doesn't work, because now they're not equal width. Turns out to be quite a tricky problem to solve.

**Comment by KaiWaldrant** [comment]
fixed it

**Comment by KaiWaldrant** [comment]
also closes #59

**Review by rcannood — APPROVED** [review]
LGTM!

**Comment by scottgigante-immunai** [comment]
This didn't work. See e.g. the advisors when ncol=2 -- because Jon's card is narrower than Fabian's card, Smita's looks off-centre. 

image

**Pull request merged**
