### PR TITLE
Put team in alphabetical order by surname

### PR DESCRIPTION
**Pull request by scottgigante-immunai**
Alphabetical by first name is weird ... better still would be random order but that seems more complicated

### CODE REVIEW

**Comment by scottgigante-immunai** [comment]
This didn't do anything ¯\_(ツ)_/¯

**Comment by KaiWaldrant** [comment]
The quarto listing automatically sorts on title and for some reason by setting sort to empty it automagically sorts on surname  ¯_(ツ)_/¯

**Comment by rcannood** [comment]
I think this behaviour makes sense based on what is written in the [documentation](https://quarto.org/docs/websites/website-listings.html#sorting-items). That is, by default a listing will be sorted by the title, not the filename. It seems setting `sort=''` will then sort by filename instead.

I'm fine with sorting the team by surname, though then I feel the listed names should also be "Gigante Scott" and not "Scott Gigante". This has the additional side-effect of coming across more formal than we may want.

@dburkhardt @scottgigante-immunai @LuckyMD What are your thoughts on this?

**Comment by rcannood** [comment]
Ok, guess I'm the one being weird here :p

**Review by rcannood — APPROVED** [review]

**Pull request merged**
