### PR TITLE
fix: update funkyheatmap

### PR DESCRIPTION
**Pull request by mxposed**
- color by rank option (#72)
- sorting arrows fix direction (#114)
- set initial sort to descending (#116)
- show back funkyheatmap controls

### CODE REVIEW

**Comment by rcannood** [comment]
Suggestions: 
* When coloring by rank, a separate rank color legend should be created
* When rescaling the x axis, the labels on the index should be "min" "max"

**Comment by mxposed** [comment]
@rcannood @scottgigante I have added the option to funkyheatmap, see this PR deploy as a demo

**Comment by mxposed** [comment]
> When coloring by rank, a separate rank color legend should be created

I don't see where best to put it (and how would it look). Yet

**Comment by rcannood** [comment]
IKR :p 

In general, the positioning of the legends in the R library is something that needed some attention. I hope we can take a look at it some point and make sure that the R and Python implementation is aligned.

**Comment by rcannood** [comment]
Disabling the input panel for now, so the 0.1.7 release can already be included into the openproblems.bio v2 release.

**Pull request merged**
