### PR TITLE
Override bad bootstrap transition css

### PR DESCRIPTION
**Pull request by scottgigante-immunai**
For some reason, bootstrap overrides its own `transform` transition with a `position` transition, which means no transition actually occurs. This fixes that.

### CODE REVIEW

**Comment by KaiWaldrant** [comment]
THis is a quarto addition to the bootstrap as it is used with the headroom.js (https://quarto.org/docs/websites/website-navigation.html#top-navigation). maybe a setting overrides this?

**Comment by scottgigante-immunai** [comment]
Both of the settings come from bootstrap.min.js. Not sure what's breaking it but it's broken, so let's fix it :)

**Comment by KaiWaldrant** [comment]
This was a quarto issue. they fixed this so should be in release 1.3 quarto-dev/quarto-cli#4715

**Comment by rcannood** [comment]
@scottgigante-immunai Does the issue referenced by Kai also solve the problem?

If so, I'd propose not merging this PR. Maybe we could even switch to a pre-release of quarto 1.3.

**Comment by scottgigante-immunai** [comment]
Yes, this will be fixed in 1.3. How about we merge this, open a new PR reverting this change, and merge that one once we update to quarto 1.3?

**Comment by rcannood** [comment]
Sounds good:)

**Pull request merged**
